/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * gameWinnerDialog.java
 *
 * Created on 28/05/2011, 01:58:37
 */
package src.ui.guiComponents.dialogs;

import java.awt.Dimension;
import java.awt.Toolkit;
import src.client.GameManager;
import src.client.ui.initgame.GamesPanel;
import src.client.ui.utils.ExamplesUtils;

/**
 *
 * @author Shachar
 */
public class gameWinnerDialog extends javax.swing.JDialog {

    /** Creates new form gameWinnerDialog */
    public gameWinnerDialog(java.awt.Frame parent, boolean modal, String winMessage) {
        super(parent, modal);
        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width/2,Toolkit.getDefaultToolkit().getScreenSize().height/2);
        this.setPreferredSize(d);
        this.setMaximumSize(d);
        this.setMinimumSize(d);
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        winnerAnnouncement.setText(winMessage);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winnerAnnouncement = new javax.swing.JLabel();
        goAgainButton = new javax.swing.JButton();
        leaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        winnerAnnouncement.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        winnerAnnouncement.setForeground(new java.awt.Color(255, 0, 0));
        winnerAnnouncement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerAnnouncement.setText("Winner announcement goes here!");
        winnerAnnouncement.setFocusable(false);
        winnerAnnouncement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        goAgainButton.setText("Start Over");
        goAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goAgainButtonActionPerformed(evt);
            }
        });

        leaveButton.setText("Exit");
        leaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(winnerAnnouncement)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goAgainButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(leaveButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(winnerAnnouncement)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goAgainButton)
                    .addComponent(leaveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goAgainButtonActionPerformed
        GameManager.currentUI.getFrame().dispose();
        ExamplesUtils.showExample("Join Game", new GamesPanel());
    }//GEN-LAST:event_goAgainButtonActionPerformed

    private void leaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_leaveButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goAgainButton;
    private javax.swing.JButton leaveButton;
    private javax.swing.JLabel winnerAnnouncement;
    // End of variables declaration//GEN-END:variables
}
